# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'

# The target name is most likely the name of your project.
target 'NumberTileGame' do
    
    # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
    'BatchedBridge',
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    
end
